// <auto-generated />
namespace ValeDoSolFinal_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class teste1x1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teste1x1));
        
        string IMigrationMetadata.Id
        {
            get { return "201906242013453_teste1x1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
