// <auto-generated />
namespace ValeDoSolFinal_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Relacionamento1N : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relacionamento1N));
        
        string IMigrationMetadata.Id
        {
            get { return "201906241921526_Relacionamento1N"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
